# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main"]
    tags: ["v*","V*"]
  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Publishing-GitHub_Release-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3
      - name: bulid exefile
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker pull cdrx/pyinstaller-windows
          docker run -v $GITHUB_WORKSPACE:/src cdrx/pyinstaller-windows:latest 'pyinstaller -F --clean -y --dist ./ --workpath /tmp ./excerpt_tool/main.py'
          mv ./main.exe ./noncode.exe
      - name: Create Release and Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: V0.${{ github.run_number }}.${{ github.run_id }}.dev
          name: V0.${{ github.run_number }}.${{ github.run_id }}.dev
          body: TODO New Release.
          draft: false
          prerelease: true
          files: |
            noncode.exe
