name: Python Package using Conda

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main"]
    tags: ["v*","V*"]
    
jobs:
  Publishing-GitHub_Release-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3
      - name: bulid exefile
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker pull cdrx/pyinstaller-windows
          docker run -v $GITHUB_WORKSPACE:/src cdrx/pyinstaller-windows:latest 'pyinstaller -F --clean -y --dist ./ --workpath /tmp ./excerpt_tool/main.py'
          mv ./main.exe ./noncode.exe
      - name: Create Release and Upload Release Asset
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: V0.${{ github.run_number }}.${{ github.run_id }}.dev
          name: V0.${{ github.run_number }}.${{ github.run_id }}.dev
          body: TODO New Release.
          draft: false
          prerelease: true
          files: |
            noncode.exe
